In [95]:
#Vatsal Ketan Patel | CS577 | A20458061 | Spring2020


import numpy as np
import math
import numpy.linalg as m

In [96]:
#A) 
A = np.array([1,2,3])
B = np.array([4,5,6])
C = np.array([-1,1,3])

In [97]:
#1) 2A-B

result = np.array([0,0,0])
result = 2*A - B
        
print(result)

[-2 -1  0]


In [98]:
#2) ||A|| and angle of A relative to positive X-axis

vector = np.array([1,0,0])

Mag_A = np.linalg.norm(A)
Mag_vector = np.linalg.norm(vector)
Mag_2 = Mag_A* Mag_vector

result3 = 0
result3 = np.dot(A,vector)        

print("Angle between A and positive X-Axis([1,0,0]) is: ", np.degrees(np.arccos(result3/Mag_2)))

Angle between A and positive X-Axis([1,0,0]) is:  74.498640433063


In [99]:
#3) A, a unit vector in the direction of A

unit_vector = np.array([0,0,0])

unit_vector = np.divide(A,Mag_A)

for uv in unit_vector:    
    print(uv)

0.2672612419124244
0.5345224838248488
0.8017837257372732


In [100]:
#4)  the direction cosines of A
Mag_A = np.linalg.norm(A)
inv = np.arccos(np.divide(A,Mag_A)) 
print("X,Y and Z Direction Cosines of A",np.degrees(inv))

X,Y and Z Direction Cosines of A [74.49864043 57.68846676 36.6992252 ]


In [101]:
#5) A · B and B · A

result1 = 0
result2 = 0 

result1 = np.dot(A,B)
result2 = np.dot(B,A)        

print("A.B = ",result1)
print("B.A = ",result2)


A.B =  32
B.A =  32


In [102]:
#6)the angle between A and B

Mag_A = np.linalg.norm(A)
Mag_B = np.linalg.norm(B)
Mag = Mag_A * Mag_B
result1 = np.dot(A,B)
theta = np.arccos(result1/Mag)
print("Angle between A & B: ",np.degrees(theta))

Angle between A & B:  12.933154491899135


In [103]:
#7)  A vector which is perpendicular to A

result4 = 0
result5 = np.array([0,0,0])
result5 = np.cross(A,B)

result4 = np.dot(result5,A)
if (result4 == 0):
    print("Vector",result5,"is perpendicular to A as the dot-product of vector A and resultant vector is 0")
else: 
    print("Vector",result5,"is not perpendicular to A a as the dot product of vector A and resultant vector is not 0")


Vector [-3  6 -3] is perpendicular to A as the dot-product of vector A and resultant vector is 0


In [104]:
#8 A X B and B X A

result5 = np.array([0,0,0])
result5 = np.cross(A,B)

result6 = np.array([0,0,0])
result6 = np.cross(B,A)

print("Cross product of A and B: ",result5)
print("Cross product of B and A: ",result6)

Cross product of A and B:  [-3  6 -3]
Cross product of B and A:  [ 3 -6  3]


In [105]:
#9 a vector which is perpendicular to both A and B

result7 = 0
result8 = 0
result9 = 0
result10 = 0


result7 = np.dot(result5, A)
result8 = np.dot(result5, B)
result9 = np.dot(result6, A)
result10 = np.dot(result6, B)
    
if (result7 == 0 and result8 ==0):
    print("Vector",result5,"is perpendicular to both A and B as the dot product of vector A and B with (A X B) respectively is 0")
else: 
    print("Vector",result5,"is not perpendicular to both A and B as the dot product of the vectors is not 0")
if (result9 == 0 and result10 ==0):
    print("Vector",result6,"is perpendicular to both A and B as the dot product of vector A and B with (B X A) respectively is 0")
else: 
    print("Vector",result6,"is not perpendicular to both A and B as the dot product of the vectors is not 0")

Vector [-3  6 -3] is perpendicular to both A and B as the dot product of vector A and B with (A X B) respectively is 0
Vector [ 3 -6  3] is perpendicular to both A and B as the dot product of vector A and B with (B X A) respectively is 0


In [108]:
#10 the linear dependency between A, B, C

ABC = np.matrix([[1,4,-1],[2,5,1],[3,6,3]])
Det_ABC = np.round(m.det(ABC))
if(Det_ABC==0):
    print("A,B,C are linearly dependent")
else:
    print("A,B,C are linearly independent")

A,B,C are linearly dependent


In [109]:
#11 A^T.B and A.B^T

result11 = 0
result12 = np.array([[0,0,0],[0,0,0],[0,0,0]])

A_trans = A.transpose()
B_trans = B.transpose()

result11 = np.dot(A_trans, B)
result12 = np.outer(A, B_trans)

print("A^T.B: ",result11)
print("A.B^T: ",result12)

A^T.B:  32
A.B^T:  [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
