In [58]:
#Vatsal Ketan Patel | CS577 | A20458061 | Spring2020

import numpy as np
import numpy.linalg as m

In [59]:
#B)

A = np.matrix([[1,2,3],[4,-2,3],[0,5,-1]])
B = np.matrix([[1,2,1],[2,1,-4],[3,-2,1]])
C = np.matrix([[1,2,3],[4,5,6],[-1,1,3]])

In [60]:
#1) 2A − B

result1 = 2*A-B
print("2A-B: ", result1)

2A-B:  [[ 1  2  5]
 [ 6 -5 10]
 [-3 12 -3]]


In [61]:
#2) AB and BA

AB = np.dot(A,B)
BA = np.dot(B,A)
print("A.B:", AB)
print("B.A:", BA)

A.B: [[ 14  -2  -4]
 [  9   0  15]
 [  7   7 -21]]
B.A: [[  9   3   8]
 [  6 -18  13]
 [ -5  15   2]]


In [62]:
#3) (AB)^T and B^T.A^T

AB_Trans = AB.getT()
B_Trans = B.getT()
A_Trans = A.getT()

B_trans_A_Trans = np.dot(B_Trans,A_Trans)
print("(AB)^T :" , AB_Trans)
print("B^T.A^T :" , B_trans_A_Trans)

(AB)^T : [[ 14   9   7]
 [ -2   0   7]
 [ -4  15 -21]]
B^T.A^T : [[ 14   9   7]
 [ -2   0   7]
 [ -4  15 -21]]


In [63]:
#4) |A| and |C|

Det_A = m.det(A)
Det_C = m.det(C)
print("|A| :", Det_A)
print("|C| :", Det_C)

|A| : 54.999999999999964
|C| : 7.494005416219837e-16


In [71]:
#5) the matrix (A, B, or C) in which the row vectors form an orthogonal set

R1 = np.array([1,2,1])
R2 = np.array([2,1,-4])
R3 = np.array([3,-2,1])

R1_R2 = np.dot(R1,R2)
R2_R3 = np.dot(R2,R3)
R1_R3 = np.dot(R1,R3)

if(R1_R2==0 and R2_R3==0 and R1_R3==0):
    print("Row Vectors from an orthogonal set")
else:
    print("Row Vectors do not form an orthognal set")

        

Row Vectors from an orthogonal set


In [52]:
#6) A^−1 and B^−1

Inverse_A = A.getI()
Inverse_B = B.getI()
print("A^-1 :" , Inverse_A)
print("B^-1 :" , Inverse_B)


A^-1 : [[-0.23636364  0.30909091  0.21818182]
 [ 0.07272727 -0.01818182  0.16363636]
 [ 0.36363636 -0.09090909 -0.18181818]]
B^-1 : [[ 0.16666667  0.0952381   0.21428571]
 [ 0.33333333  0.04761905 -0.14285714]
 [ 0.16666667 -0.19047619  0.07142857]]
